const express = require('express');
const router = express.Router();

// Project data
const projects = [
  {
    id: 'safisend',
    title: 'SafiSend — Restaurant Commerce Platform with a Personalized Menu Recommender',
    description: 'SafiSend is a production restaurant technology platform I founded and lead as product and engineering lead, deployed at www.safisend.com. Customers scan a QR code to browse, order, and pay from their phone. Underneath the ordering flow I built the platform\'s machine learning layer: a hybrid recommender that personalizes the menu per diner by combining OpenAI embeddings, collaborative filtering, and a from-scratch FP-Growth market basket miner, plus a GPT-4o Vision OCR pipeline that onboards a restaurant by reading its existing paper menu. The system spans ~144k lines across 57 data models and 156 services, with 859 commits and 68 test suites.',
    challenges: 'The hardest problem was recommendation cold start. A diner scanning a QR code is frequently anonymous, has no order history, and will leave within minutes — so there is no time to learn preferences the usual way. I solved it with a five-tier strategy ladder that degrades gracefully (personalized → session learning → cross-restaurant transfer → new customer → anonymous), including a platform-level taste profile that transfers a returning customer\'s preferences to a restaurant they have never visited. Because every embedding is generated by the same model, "spicy chicken" at one restaurant lands near "fiery wings" at another in the same 1536-dimensional space. That capability had to be built without leaking data across restaurant boundaries: the transfer is confidence-gated, blended at low weight, decayed to zero as local orders accumulate, and opt-out. The other significant challenge was menu onboarding — restaurants arrive with a PDF or a photo, so extraction had to be accurate enough to trust without manual re-entry.',
    image: '/assets/img/projects/safisend.jpg',
    technologies: [
      { name: 'OpenAI Embeddings', icon: 'fas fa-brain' },
      { name: 'GPT-4o Vision', icon: 'fas fa-eye' },
      { name: 'FP-Growth', icon: 'fas fa-project-diagram' },
      { name: 'React', icon: 'fab fa-react' },
      { name: 'Node.js', icon: 'fab fa-node-js' },
      { name: 'MongoDB', icon: 'fas fa-database' },
      { name: 'WhatsApp API', icon: 'fab fa-whatsapp' },
      { name: 'M-Pesa', icon: 'fas fa-mobile-alt' },
      { name: 'Docker', icon: 'fab fa-docker' },
      { name: 'Nginx', icon: 'fas fa-cloud' },
      { name: 'JMeter', icon: 'fas fa-chart-bar' }
    ],
    date: 'Aug 2025 – May 2026',
    category: 'AI/ML · Recommender Systems · Product',
    liveUrl: 'https://www.safisend.com',
    technicalAchievements: [
      'Hybrid recommender ranking every menu item on five weighted signals — semantic similarity (0.35), collaborative filtering (0.20), behavioral taste profile (0.20), live popularity (0.15), and recency (0.10) — then applying diversity enforcement and context-aware filtering for menu, cart, and checkout surfaces',
      'Five-tier cold-start ladder (personalized → session learning → platform transfer → new customer → anonymous) so an anonymous first-time diner still gets a meaningfully ranked menu instead of a default sort',
      'Cross-restaurant transfer learning: a platform taste profile aggregates a customer\'s per-restaurant embeddings weighted by order count and recency into an L2-normalized vector, letting a returning diner get personalized results at a restaurant they have never visited — gated at ≥5 orders across ≥2 restaurants, blended at 30% and decaying to 0% as local history grows, with no cross-restaurant data exposure',
      'FP-Growth market basket analysis implemented from scratch in dependency-free JavaScript (FP-tree construction, header tables with node links, recursive conditional pattern base mining) following Han, Pei & Yin (2000), unit tested and mining frequent itemsets and association rules scored by support, confidence, lift, and conviction',
      'Semantic embedding engine over OpenAI text-embedding-3-small: 1536-dimensional item and customer vectors, customer vectors computed as L2-normalized weighted averages of ordered items, cosine similarity matching, batch generation, and an LRU-style cache with hit/miss instrumentation',
      'Real-time session learning that blends a live session embedding with the stored customer vector (70/30), so recommendations adapt to what the diner is browsing within a single sitting',
      'GPT-4o Vision menu OCR with a multi-pass accuracy strategy: Sharp-based image preprocessing, a first extraction pass, then a focused second pass that re-analyzes only items scoring below the 0.85 confidence threshold before merging results — plus currency detection, category inference, dietary attribute inference, and confidence scores that route uncertain items to human review',
      'Closed-loop recommendation analytics: impression, click, and add-to-cart events are logged per surface with the originating strategy and score, giving compound-indexed data to evaluate which recommendation sources actually convert',
      'Upsell engine classifying premium upgrades, add-ons, and meal completers scored on embedding similarity (0.50), price uplift (0.30), and co-purchase rate (0.20), precomputed by a scheduled mining job',
      'Production commerce foundation: QR-to-order with no app install, real-time split billing, WhatsApp Business API notifications, M-Pesa payment callbacks and reconciliation, live kitchen dashboard, Dockerized services behind Nginx, and JMeter load testing to 500+ concurrent users'
    ]
  },
  {
    id: 'kaizen',
    title: 'Kaizen — AI-Native Personal Operating System',
    description: 'Kaizen is an AI-native personal operating system for habits, goals, journaling, and reviews. Its differentiator is an AI Coach that reads and writes the user\'s real data rather than just chatting about it: a streaming tool-use loop gives the model 12 tools that map onto the exact same service-layer functions the REST API uses, so the agent mutates state through identical, validated code paths as the UI. Built on FastAPI + SQLAlchemy 2.0 with Postgres/pgvector and a Next.js App Router frontend.',
    challenges: 'The core problem was making an LLM a trustworthy actor on production data instead of a chat surface bolted onto a CRUD app. That meant binding tools to shared service functions so the agent could not create a divergent write path, grounding the model in real state (dashboard reads before advice, injected current date and timezone so relative dates like "tomorrow at 7am" resolve to correct ISO datetimes), streaming tool activity to the client over SSE so multi-round tool use stays legible, and bounding the agent loop. A second challenge was vendor neutrality: designing one provider interface so Anthropic Claude and OpenAI implement the same streaming contract, plus graceful degradation when no API key is configured at all.',
    image: '/assets/img/projects/project-cover.svg',
    technologies: [
      { name: 'Anthropic Claude', icon: 'fas fa-brain' },
      { name: 'Python', icon: 'fab fa-python' },
      { name: 'FastAPI', icon: 'fas fa-bolt' },
      { name: 'SQLAlchemy', icon: 'fas fa-database' },
      { name: 'Postgres + pgvector', icon: 'fas fa-vector-square' },
      { name: 'Next.js', icon: 'fab fa-react' },
      { name: 'Tailwind CSS', icon: 'fab fa-css3-alt' },
      { name: 'Docker', icon: 'fab fa-docker' }
    ],
    date: '2026',
    category: 'AI Engineering · Agentic Systems',
    technicalAchievements: [
      'Agentic tool-use loop: 12 tools (create_goal, log_habit, add_journal_entry, generate_review, schedule_event, send_email, and more) dispatched against the same service layer the REST API calls, so the agent writes through validated, non-divergent code paths',
      'Provider-neutral LLM abstraction: a single stream_agent contract implemented by both an Anthropic provider (streaming with adaptive thinking, preserving thinking and redacted_thinking blocks across tool rounds) and an OpenAI provider (function calling), selected at runtime by a factory from whichever key is present',
      'Server-Sent Events streaming: tokens and tool invocations are pushed to the chat UI live, so multi-round tool use renders as visible activity instead of a long silent wait',
      'Prompt grounding for correctness: the system prompt injects the user\'s real timezone and current datetime so relative scheduling ("tomorrow at 7am") resolves to exact ISO datetimes, and instructs the model to read dashboard state before giving progress advice',
      'Semantic knowledge search over pgvector with a pluggable embedding backend (Voyage AI or OpenAI, both normalized to 1024 dimensions so the vector column stays provider-agnostic) and automatic keyword fallback',
      'Natural-language capture: a structured-output LLM call turns one free-form sentence into a typed goal/habit/journal draft returned as strict JSON, surfaced as an editable confirm card',
      'Bounded, resilient agent execution: iteration-capped tool loop, and every AI path degrades gracefully to a clear message when no API key is configured — the rest of the app stays fully usable',
      'Google Calendar OAuth (read + write) with tokens encrypted at rest via Fernet, making the Coach schedule-aware and able to create real calendar events',
      'Full-stack delivery: 14-table relational model, ~7.5k lines across a FastAPI backend and Next.js App Router frontend, Dockerized Postgres + pgvector'
    ]
  },
  {
    id: 'takeyourvitamins',
    title: 'TakeYourVitamins - Health Management API',
    description: 'TakeYourVitamins is a comprehensive Flask-based API for managing vitamin information with MongoDB integration. The system features a robust RESTful API with Swagger documentation, automated testing with Selenium for end-to-end testing, load testing with JMeter supporting up to 1000 concurrent users, and a complete CI/CD pipeline with GitHub Actions. The project includes comprehensive data models for vitamins, supplements, and user interactions with detailed intake practices and interaction warnings.',
    challenges: 'Key challenges included implementing comprehensive automated testing with Selenium for browser-based end-to-end testing, designing efficient MongoDB data models for complex vitamin interaction data, creating a robust CI/CD pipeline with multiple testing stages, and implementing load testing capabilities to ensure system scalability. The project required careful API design to handle complex supplement interaction data and user intake tracking while maintaining performance under high load.',
    image: '/assets/img/projects/takeyourvitamins.jpg',
    technologies: [
      { name: 'Python', icon: 'fab fa-python' },
      { name: 'Flask', icon: 'fas fa-flask' },
      { name: 'MongoDB', icon: 'fas fa-database' },
      { name: 'Selenium', icon: 'fas fa-robot' },
      { name: 'JMeter', icon: 'fas fa-chart-bar' },
      { name: 'GitHub Actions', icon: 'fab fa-github' },
      { name: 'Swagger', icon: 'fas fa-book' },
      { name: 'pytest', icon: 'fas fa-vial' },
      { name: 'TypeScript', icon: 'fab fa-js-square' }
    ],
    date: 'December 2024',
    category: 'Backend API & Testing',
    githubUrl: 'https://github.com/EnockMagara/TakeYourVitamins',
    technicalAchievements: [
      'Comprehensive API Design: Built RESTful API with full CRUD operations for vitamin management with Swagger documentation',
      'Automated Testing Suite: Implemented Selenium-based end-to-end testing with screenshot capture for debugging',
      'Load Testing Infrastructure: Configured JMeter for performance testing supporting up to 1000 concurrent users',
      'CI/CD Pipeline: Established GitHub Actions workflow with automated testing, linting, formatting, and coverage reporting',
      'Data Modeling: Designed complex MongoDB schemas for vitamins, supplements, interactions, and intake practices',
      'Test Automation: Created comprehensive test suite with unit tests, integration tests, and system tests',
      'Documentation: Implemented Swagger UI for interactive API documentation and testing',
      'Performance Optimization: Achieved high performance and scalability through efficient database design and caching strategies'
    ]
  },
  {
    id: 'safipoints',
    title: 'SafiPoints — Blockchain Loyalty Rewards on XRPL',
    description: 'Blockchain-powered loyalty and cashback system for restaurants, built on the XRP Ledger. Customers earn SAFI tokens automatically when they pay via SafiSend, store them on-chain, and redeem for discounts at checkout. Extended with SafiScore — a verifiable on-chain credit profile built from retail spending history. Selected as 1 of 15 fellows at the Ripple XRPL Builder Residency; presented at Ripple Demo Day, London.',
    challenges: 'Designing a seamless token mint-and-redeem flow that works invisibly inside a real restaurant ordering session, handling XRPL testnet latency, SMS OTP claim for first-time users, and building a verifiable on-chain credit score from spend history using Solidity on the XRPL EVM Sidechain.',
    image: '/assets/img/projects/safipoints.jpg',
    technologies: [
      { name: 'React', icon: 'fab fa-react' },
      { name: 'Node.js', icon: 'fab fa-node-js' },
      { name: 'XRPL', icon: 'fas fa-link' },
      { name: 'Solidity', icon: 'fas fa-file-code' },
      { name: 'MongoDB', icon: 'fas fa-database' },
      { name: 'Docker', icon: 'fab fa-docker' },
      { name: 'Nginx', icon: 'fas fa-cloud' }
    ],
    date: 'Mar – Apr 2026',
    category: 'Blockchain · Fintech · DeFi',
    githubUrl: 'https://github.com/EnockMagara/SAFIPOINTS',
    technicalAchievements: [
      'SAFI token minted on XRPL Testnet as IOU: 10% cashback auto-minted on every qualifying payment',
      'SMS OTP claim flow for first-time users; returning customers get auto-minted tokens',
      'SafiScore: verifiable on-chain credit profile built from retail spend history, using Solidity smart contracts on XRPL EVM Sidechain',
      'Full React SPA with Framer Motion animations, custom CSS, connected to Express/MongoDB backend',
      'Dockerized deployment behind Nginx with SSL; seed scripts to bootstrap XRPL wallets and demo data',
      'Selected as 1 of 15 XRPL Builder Residency fellows; presented live at Ripple Demo Day, London'
    ]
  },
  {
    id: 'quantopt',
    title: 'QuantOpt - AI Portfolio Optimization',
    description: 'A comprehensive machine learning system for portfolio optimization using PySpark and PyTorch. Implements Modern Portfolio Theory optimizers, Deep Reinforcement Learning (DDPG/PPO) for dynamic rebalancing, and Monte Carlo risk simulations with robust backtesting and evaluation.',
    challenges: 'Designing a unified pipeline that scales from classical optimization to deep RL while ensuring reproducibility, robust feature engineering, and realistic backtesting with transaction costs and stress scenarios.',
    image: '/assets/img/projects/project-cover.svg',
    technologies: [
      { name: 'Python', icon: 'fab fa-python' },
      { name: 'PySpark', icon: 'fas fa-bolt' },
      { name: 'PyTorch', icon: 'fas fa-fire' },
      { name: 'CVXPY', icon: 'fas fa-calculator' },
      { name: 'Reinforcement Learning', icon: 'fas fa-brain' }
    ],
    date: '2025',
    category: 'Quant Finance & ML',
    githubUrl: 'https://github.com/EnockMagara/QuantOpt',
    technicalAchievements: [
      'End-to-end pipeline: preprocessing, feature engineering, modeling, and evaluation with PySpark + PyTorch',
      'Multiple optimizers: MPT (max Sharpe, min variance), Deep RL rebalancing (DDPG/PPO), and Monte Carlo risk',
      'Backtesting framework with stress testing (e.g., 2008-like crash scenarios) and rich metrics',
      'Config-driven architecture with reproducible runs and scalable data handling',
      'Extensible module layout with unit tests and results reporting'
    ]
  },
  {
    id: 'mapreducemlops',
    title: 'Movie Review Sentiment Analysis (MapReduce + ML)',
    description: 'A comprehensive MLOps project for sentiment analysis of movie reviews using Apache Spark MapReduce and machine learning. Includes Spark-based TF-IDF feature extraction, MLlib models (Naive Bayes, Logistic Regression, Random Forest), PyTorch deep learning variants (LSTM/Transformer/BERT), MLflow tracking, Docker, and Makefile-driven workflows.',
    challenges: 'Designing a unified pipeline supporting both Spark MLlib and PyTorch while maintaining reproducibility and comparability. Implementing TF-IDF at scale, robust experiment tracking with MLflow, and containerized, repeatable training/inference flows. Balancing performance and resource usage across distributed and GPU workloads.',
    image: '/assets/img/projects/mlops.png',
    technologies: [
      { name: 'Apache Spark', icon: 'fas fa-bolt' },
      { name: 'Python', icon: 'fab fa-python' },
      { name: 'PyTorch', icon: 'fas fa-fire' },
      { name: 'MLflow', icon: 'fas fa-chart-line' },
      { name: 'Docker', icon: 'fab fa-docker' },
      { name: 'Make', icon: 'fas fa-cogs' }
    ],
    date: '2025',
    category: 'MLOps & Distributed ML',
    githubUrl: 'https://github.com/EnockMagara/MapReduceMLOps',
    technicalAchievements: [
      'Hybrid Pipeline: Unified Spark MapReduce feature engineering with parallel PyTorch deep learning path',
      'Model Zoo: Implemented Naive Bayes, Logistic Regression, Random Forest, plus LSTM/Transformer/BERT variants',
      'Experiment Tracking: Full MLflow integration with metrics, params, and artifact logging',
      'Reproducibility: Makefile + Docker workflows for install, train, evaluate, and predict',
      'Scalability: Distributed TF-IDF and training with Spark, GPU-ready PyTorch training scripts',
      'CI-ready Structure: Config-driven scripts, tests, and modular code layout for extension'
    ]
  },
  {
    id: 'jobboard',
    title: 'JobBoard - Full-Stack Job Platform',
    description: 'JobBoard is a comprehensive full-stack job platform built with Python/Flask backend and Next.js frontend, featuring dual user authentication for companies and job seekers. The platform includes advanced A/B testing capabilities using LLM-enhanced job descriptions, comprehensive API endpoints for job management, and automated CI/CD pipeline with Docker containerization. The system implements sophisticated analytics and conversion tracking to optimize job posting effectiveness.',
    challenges: 'Key challenges included implementing a robust dual authentication system for different user types, creating an efficient A/B testing framework for job descriptions using Together.ai LLM integration, and developing a comprehensive API with proper authorization and data validation. The project required complex database design to handle job applications, user management, and analytics tracking while maintaining performance and scalability.',
    image: '/assets/img/projects/jobboard.jpg',
    technologies: [
      { name: 'Python', icon: 'fab fa-python' },
      { name: 'Flask', icon: 'fas fa-flask' },
      { name: 'Next.js', icon: 'fab fa-react' },
      { name: 'MongoDB', icon: 'fas fa-database' },
      { name: 'Docker', icon: 'fab fa-docker' },
      { name: 'GitHub Actions', icon: 'fab fa-github' },
      { name: 'Together.ai', icon: 'fas fa-robot' },
      { name: 'JWT', icon: 'fas fa-lock' },
      { name: 'RESTful API', icon: 'fas fa-server' }
    ],
    date: 'January 2025',
    category: 'Full-stack Web Application',
    githubUrl: 'https://github.com/EnockMagara/jobboard-public',
    technicalAchievements: [
      'Dual Authentication System: Implemented separate authentication flows for companies and job seekers with role-based access control',
      'A/B Testing Framework: Built comprehensive A/B testing system comparing original vs LLM-enhanced job descriptions with conversion tracking',
      'RESTful API Design: Created 20+ API endpoints with proper HTTP methods, status codes, and comprehensive error handling',
      'LLM Integration: Integrated Together.ai for automated job description enhancement and optimization',
      'Analytics Dashboard: Developed conversion tracking and visualization system with charts and statistical analysis',
      'Docker Containerization: Implemented containerized deployment with proper environment configuration and dependency management',
      'CI/CD Pipeline: Established automated testing, building, and deployment workflow using GitHub Actions',
      'Database Design: Created optimized MongoDB schemas for companies, job seekers, job posts, and applications with proper indexing'
    ]
  },
  {
    id: 'cloudtrace',
    title: 'CloudTrace - Cloud Provider Benchmark',
    description: 'CloudTrace is a high-performance network analysis tool leveraging raw ICMP sockets to benchmark connectivity metrics to major cloud providers. Built on Python/Flask with modular architecture, it performs multi-point traceroute analysis with precise RTT measurements and geospatial visualization. I implement a comprehensive CI/CD pipeline for automated testing and deployment, along with extensive unit testing to ensure reliability.',
    challenges: 'One of the key challenges was implementing a custom socket-level ICMP implementation with packet crafting while ensuring proper privilege escalation handling and fallback visualization for permission-restricted environments. The project also required complex statistical aggregation with outlier identification and geographic path visualization with cross-border transit detection.',
    image: '/assets/img/projects/cloudtrace.png',
    technologies: [
      { name: 'Python', icon: 'fab fa-python' },
      { name: 'Flask', icon: 'fas fa-flask' },
      { name: 'JavaScript', icon: 'fab fa-js-square' },
      { name: 'SQLite', icon: 'fas fa-database' },
      { name: 'AJAX', icon: 'fas fa-sync-alt' },
      { name: 'Plotly.js', icon: 'fas fa-chart-line' }
    ],
    date: 'March 2025',
    category: 'Network Analysis',
    liveUrl: 'https://cloudtrace.duckdns.org/',
    githubUrl: 'https://github.com/EnockMagara/CloudTrace-Benchmark'
  },
  {
    id: 'hackheist',
    title: 'AYN - AI-Powered Visual Assistant',
    description: 'AYN is an advanced visual assistance application designed to help visually impaired users navigate and understand their surroundings. This full-stack application combines machine learning-based object detection with natural language processing to provide real-time audio descriptions of environments captured by the camera. The system features a Flask backend that integrates YOLOv5 for object detection and MiDaS for depth estimation, along with a sleek Next.js frontend with responsive design and accessible UI.',
    challenges: 'Key challenges included implementing robust real-time object detection with spatial awareness, creating an accessible and intuitive UI for visually impaired users, and developing an efficient pipeline for processing video frames and generating meaningful audio descriptions. The project required integrating multiple machine learning models and ensuring they worked together seamlessly while maintaining low latency for real-time feedback.',
    image: '/assets/img/projects/hackheist.jpg',
    technologies: [
      { name: 'Python', icon: 'fab fa-python' },
      { name: 'Flask', icon: 'fas fa-flask' },
      { name: 'PyTorch', icon: 'fas fa-fire' },
      { name: 'Next.js', icon: 'fab fa-react' },
      { name: 'React', icon: 'fab fa-react' },
      { name: 'Tailwind CSS', icon: 'fab fa-css3-alt' },
      { name: 'OpenAI API', icon: 'fas fa-robot' },
      { name: 'YOLOv5', icon: 'fas fa-eye' },
      { name: 'MiDaS', icon: 'fas fa-mountain' }
    ],
    date: 'February 2025',
    category: 'AI & Accessibility',
    liveUrl: 'https://drive.google.com/file/d/1Wl9L5GRE-5ZyQLFlioMG-RcnTCGqplIT/view?usp=share_link',
    githubUrl: 'https://github.com/Danjari/hackheist',
    technicalAchievements: [
      'Multi-Model AI System: Integrated YOLOv5 for object detection and MiDaS for depth estimation to create comprehensive spatial awareness',
      'Real-time Processing: Implemented efficient video frame processing with WebRTC for camera access and canvas manipulation',
      'Depth-Based Object Prioritization: Created an algorithm to identify and prioritize nearby objects based on depth estimation',
      'Natural Language Generation: Used GPT-4o to translate technical object data into natural, helpful descriptions for users',
      'Text-to-Speech Integration: Implemented OpenAI\'s TTS API to convert descriptions into clear audio feedback',
      'Accessibility-First Design: Built a UI specifically optimized for users with visual impairments, featuring large buttons and voice feedback',
      'Cross-Platform Compatibility: Ensured the application works across different devices and browsers with responsive design'
    ]
  },
  {
    id: 'mapjournal',
    title: 'MapJournal - iOS Location Sharing App',
    description: 'MapJournal is an iOS application built with SwiftUI that allows users to discover, save, and share their favorite places. The app features interactive mapping with MapKit and CoreLocation, secure user authentication via Google Sign-In, and real-time data synchronization using Firebase. Users can add detailed information to saved locations including tags, descriptions, and images, then easily share these locations with others.',
    challenges: 'Key challenges included implementing a complete location services system with proper permission handling, designing an efficient data structure for storing location data in Firestore, creating a seamless authentication flow with Google Sign-In, and building an intuitive UI for map interaction. The project required careful planning to ensure smooth integration between multiple frameworks while maintaining excellent performance.',
    image: '/assets/img/projects/mapjournal.jpg',
    technologies: [
      { name: 'Swift', icon: 'fab fa-swift' },
      { name: 'SwiftUI', icon: 'fab fa-apple' },
      { name: 'CoreLocation', icon: 'fas fa-map-marker-alt' },
      { name: 'MapKit', icon: 'fas fa-map' },
      { name: 'Firebase', icon: 'fas fa-database' },
      { name: 'Google Sign-In', icon: 'fab fa-google' },
      { name: 'Xcode', icon: 'fas fa-code' }
    ],
    date: 'November 2024',
    category: 'Mobile Development',
    liveUrl: 'https://drive.google.com/file/d/1QkNvNutOjk3Q9SezRdckK_e_FsCcYred/view?usp=sharing',
    githubUrl: 'https://github.com/EnockMagara/molab-2024-09-Enock/tree/main/WEEK10',
    technicalAchievements: [
      'Location Services: Implemented comprehensive location tracking and region monitoring using CoreLocation with user privacy considerations',
      'Map Integration: Designed an interactive map interface with custom annotations, location selection, and geocoding functionality',
      'Cloud Integration: Set up Firestore database with optimized data models for efficient querying and real-time updates',
      'Authentication System: Integrated Google Sign-In for secure user authentication and profile management',
      'Photo Management: Implemented photo selection, storage, and retrieval system with Firebase Storage',
      'Sharing Features: Created a flexible sharing system allowing users to share locations across multiple platforms',
      'MVVM Architecture: Structured the app following MVVM design pattern for better separation of concerns and maintainability'
    ]
  },
  {
    id: 'assignflow',
    title: 'AssignFlow - Task Management System',
    description: 'AssignFlow is a robust task management platform built with a modern Node.js/Express stack and MongoDB integration. This application leverages a comprehensive MVC architecture to provide dynamic task allocation, intuitive project management, and real-time notification systems. The platform features a RESTful API backend with JWT authentication, efficient in-memory caching for performance optimization, and a responsive EJS-powered templating system with modular component architecture. The deployment infrastructure utilizes a fully automated CI/CD pipeline through GitHub Actions with seamless integration for continuous deployment to production servers.',
    challenges: 'One significant challenge was implementing an intelligent task prioritization algorithm that balances workload distribution while respecting user-specified dependencies and deadlines. The system also required creating a sophisticated notification engine with multiple delivery channels and customizable triggers based on task state transitions.',
    image: '/assets/img/projects/assignflow.png',
    technologies: [
      { name: 'Node.js', icon: 'fab fa-node-js' },
      { name: 'Express', icon: 'fas fa-server' },
      { name: 'MongoDB', icon: 'fas fa-database' },
      { name: 'EJS', icon: 'fas fa-file-code' },
      { name: 'GitHub Actions', icon: 'fab fa-github' },
      { name: 'Nginx', icon: 'fas fa-cloud' }
    ],
    date: 'December 2024',
    category: 'Full-stack web development',
    liveUrl: 'https://assignflow.duckdns.org/'
  },
  {
    id: 'calmingspace',
    title: 'Calming Space - Meditation & Relaxation App',
    description: 'Calming Space is a full-stack meditation and relaxation application designed to create a personalized sanctuary for mindfulness. It features ambient sound mixing, a mindfulness timer, user authentication, and Spotify integration. Users can mix different ambient sounds (rain, forest, ocean), use a meditation timer, and play music from a curated collection or their Spotify playlists.',
    challenges: 'The key challenges included implementing a responsive audio mixing interface with precise volume controls, setting up secure authentication with both local and OAuth strategies for Spotify, and developing a CI/CD pipeline for automated testing and deployment. I also had to ensure the audio synchronization worked flawlessly across different devices and browsers.',
    image: '/assets/img/projects/calmingspace.jpg',
    technologies: [
      { name: 'Node.js', icon: 'fab fa-node-js' },
      { name: 'Express', icon: 'fas fa-server' },
      { name: 'MongoDB', icon: 'fas fa-database' },
      { name: 'JavaScript', icon: 'fab fa-js-square' },
      { name: 'CSS3', icon: 'fab fa-css3-alt' },
      { name: 'EJS', icon: 'fas fa-file-code' },
      { name: 'Passport.js', icon: 'fas fa-passport' },
      { name: 'Spotify API', icon: 'fab fa-spotify' },
      { name: 'WebAudio API', icon: 'fas fa-volume-up' },
      { name: 'OAuth2', icon: 'fas fa-lock' },
      { name: 'GitHub Actions', icon: 'fab fa-github' }
    ],
    date: 'October 2024',
    category: 'Full-stack Web Application',
    liveUrl: 'https://calmingspace.duckdns.org/dashboard',
    githubUrl: 'https://github.com/EnockMagara/calming_space',
    technicalAchievements: [
      'Custom Audio Engine: Implemented a WebAudio API-based system that allows users to mix and control multiple audio sources simultaneously with volume adjustment',
      'OAuth Integration: Securely implemented Spotify OAuth2 authentication flow, enabling users to access and play their personal music library',
      'Responsive UI/UX: Created an intuitive interface with CSS animations and responsive design principles that works across all devices',
      'Session Management: Built a robust user authentication system using Passport.js with secure cookie handling and MongoDB session storage',
      'CI/CD Pipeline: Established a GitHub Actions workflow for automated testing and deployment to a Digital Ocean cloud server',
      'HTTPS Security: Configured SSL/TLS with automatic certificate renewal via Let\'s Encrypt for secure HTTPS connections',
      'API Integration: Developed RESTful endpoints to interact with Spotify\'s Web API and WebPlayback SDK for music streaming functionality'
    ]
  },
  {
    id: 'moraamema',
    title: 'MoraaMema Initiative - Non-Profit Website',
    description: 'Designed and developed the official website for MoraaMema Initiative Inc., a non-profit organization dedicated to improving the lives of underprivileged children in Kenya through educational initiatives. The website serves as the organization\'s primary online presence, providing information about their mission, vision, projects, and facilitating donations.',
    challenges: 'The key challenge was creating a visually engaging yet lightweight website that would function well in regions with limited internet connectivity. I implemented progressive loading techniques and optimized media assets while maintaining a professional aesthetic that effectively communicates the organization\'s mission and impact.',
    image: '/assets/img/projects/moraamema.jpg',
    technologies: [
      { name: 'HTML5', icon: 'fab fa-html5' },
      { name: 'CSS3', icon: 'fab fa-css3-alt' },
      { name: 'JavaScript', icon: 'fab fa-js' },
      { name: 'Bootstrap', icon: 'fab fa-bootstrap' },
      { name: 'Responsive Design', icon: 'fas fa-mobile-alt' }
    ],
    date: 'July 2024',
    category: 'web development',
    liveUrl: 'https://moraamema.org/'
  },
];

// Route for portfolio page (projects listing)
router.get('/', (req, res) => {
  res.render('portfolio', { projects });
});

// Route for individual project details
router.get('/:id', (req, res) => {
  const projectId = req.params.id;
  const project = projects.find(p => p.id === projectId);
  
  if (!project) {
    return res.status(404).send('Project not found');
  }
  
  res.render('project-detail', { project });
});

// Export projects data for use in other files if needed
module.exports = {
  router,
  projects
};
