name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the latest code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.1' # Use the same Node.js version as your server (v18.19.1)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Write SSH private key to a file
      - name: Write SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SFTP_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      # Step 5: Deploy files to the server via SSH
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          REMOTE_HOST: ${{ secrets.SFTP_HOST }}
          REMOTE_USER: ${{ secrets.SFTP_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SFTP_PRIVATE_KEY }}
          SOURCE: "./"
          TARGET: "/root/portfolioServer/"
          ARGS: "-rltgoDzvO --delete --exclude='.git' --exclude='.github' --exclude='node_modules'"

      # Step 6: SSH into the server and restart the service
      - name: Restart portfolio.service
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          key: ${{ secrets.SFTP_PRIVATE_KEY }}
          script: |
            cd /root/portfolioServer
            npm install # Ensure dependencies are installed on the server
            sudo systemctl restart portfolio.service